version: "3.8"

services:

  json-server:
    image: vimagick/json-server 
    command: -H 0.0.0.0 -p 3000 -w scrumboard.json
    ports:
      - "3000:3000"
    volumes:
      - ./server:/data
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/
      - KEYCLOAK_REALM=test
      - KEYCLOAK_CLIENT_ID=frontend
    depends_on:
      - keycloak
      - json-server
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    volumes:
      - ./exported-realm.json:/opt/keycloak/data/import/exported-realm.json
    command:
      - "start-dev --import-realm --http-relative-path /auth"
    depends_on:
      - postgres


  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./infra/postgres:/docker-entrypoint-initdb.d
volumes:
  postgres:


