name: Push and scan dockerhub containers

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: dokwerker777/keycloak_cyber:frontend
      
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: dokwerker777/keycloak_cyber:frontend
          dockerfile: ./Dockerfile
          
      - name: Build and push dockercompose
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dokwerker777/keycloak_cyber:dockercompose
      
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          severity_threshold: HIGH
          image: dokwerker777/keycloak_cyber:dockercompose
          dockerfile: ./Dockerfile
          
        
          
